apiVersion: sample-app.weave.works/v1alpha1
kind: Car
metadata:
  creationTimestamp: null
  name: foo
  namespace: default
spec:
  brand: SAAB
  engine: The best one
  yearModel: "2008"
status:
  acceleration: 0
  distance: 7465996611147646851
  persons: 0
  speed: 18.787682655068803
