apiVersion: ignite.weave.works/v1alpha1
kind: VM
metadata:
  name: my-vm
  uid: "5121287c6564adee"
spec:
  image:
    ociClaim:
      ref: centos:7
  cpus: 2
  diskSize: 4GB
  memory: 1GB
  ssh: true
status:
  state: Running
