apiVersion: ignite.weave.works/v1alpha2
kind: VM
metadata:
  created: "2020-06-08T12:31:20Z"
  name: dark-glade
  uid: f53b6d04e98ecf56
spec:
  cpus: 1
  diskSize: 4GB
  image:
    oci: weaveworks/ignite-ubuntu:latest
  kernel:
    cmdLine: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp
    oci: weaveworks/ignite-kernel:4.19.125
  memory: 512MB
  network: {}
  sandbox:
    oci: weaveworks/ignite:v0.7.0
  storage: {}
status:
  running: true
