apiVersion: ignite.weave.works/v1alpha1
kind: VM
metadata:
  created: "2019-07-30T12:08:14Z"
  name: second-vm
  uid: 6121287c6564adee
spec:
  cpus: 2
  diskSize: 4GB
  image:
    ociClaim:
      ref: weaveworks/ignite-ubuntu:latest
      type: Docker
  kernel:
    cmdLine: console=ttyS0 reboot=k panic=1 pci=off ip=dhcp
    ociClaim:
      ref: weaveworks/ignite-kernel:4.19.47
      type: Docker
  memory: 512MB
  network:
    mode: docker-bridge
  ssh: true
status:
  image:
    id: ""
    size: 0B
  kernel:
    id: ""
    size: 0B
  state: Running
